"""
Agent Identity: the self-model that emerges from memory.

Shift 5: Identity is not narrated — it's computed from the graph.
What you keep returning to IS your identity. Dense connection clusters
ARE your concerns. High-confidence beliefs ARE your values. Low-confidence
beliefs ARE your questions. The shape of the graph IS who you are.

Identity emerges from:
1. IdentityKernel — invariants (values, boundaries, preferences), append-only
2. Persistent concerns — what the agent keeps encoding/retrieving
3. Belief system — what the agent holds true (from graph)
4. Living questions — what the agent is uncertain about (from graph)
5. Growth — how concerns and beliefs have shifted over time
6. Epoch snapshots — developmental phases with transition triggers
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone

import ulid as _ulid_mod

def _gen_ulid() -> str:
    if hasattr(_ulid_mod, 'new'):
        return str(_ulid_mod.new())
    from ulid import ULID
    return str(ULID())


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass
class EpochState:
    """A developmental phase in the agent's identity evolution.

    Epochs transition when significant formative experiences occur.
    Each epoch captures a snapshot of the agent's understanding at that phase.
    """

    epoch_number: int = 0
    started_at: str = field(default_factory=_now_iso)

    self_summary: str = ""
    """The agent's narrative understanding of itself at this epoch.
    Not a list of facts — a coherent story generated by the reflection pass."""

    user_summary: str = ""
    """The agent's understanding of its primary user at this epoch."""

    open_questions: list[str] = field(default_factory=list)
    """What was uncertain/unresolved at this epoch."""

    key_engram_ids: list[str] = field(default_factory=list)
    """Most significant memories from this epoch."""

    trigger_event: str | None = None
    """What caused the transition to the next epoch."""

    def to_dict(self) -> dict:
        return {
            "epoch_number": self.epoch_number,
            "started_at": self.started_at,
            "self_summary": self.self_summary,
            "user_summary": self.user_summary,
            "open_questions": self.open_questions,
            "key_engram_ids": self.key_engram_ids,
            "trigger_event": self.trigger_event,
        }

    @classmethod
    def from_dict(cls, d: dict) -> EpochState:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


@dataclass
class IdentityProfile:
    """Identity computed from the graph — not narrated, measured.

    Shift 5: Instead of asking an LLM "who am I?", we compute identity
    from the topology of the connection graph. What the agent keeps
    returning to IS its identity.
    """

    persistent_concerns: list[tuple[str, int]] = field(default_factory=list)
    """Tags ranked by frequency across all engrams. What you keep thinking about."""

    core_beliefs: list[tuple[str, float]] = field(default_factory=list)
    """Beliefs ranked by confidence. What you hold true."""

    living_questions: list[str] = field(default_factory=list)
    """Low-confidence beliefs + unresolved themes. What you're uncertain about."""

    hub_concepts: list[tuple[str, int]] = field(default_factory=list)
    """Engrams with most connections — the central nodes of understanding."""

    lessons_accumulated: int = 0
    """Count of procedural/lesson engrams — accumulated wisdom."""

    growth_signal: str = ""
    """How concerns have shifted since last epoch. Measured, not narrated."""

    computed_at: str = field(default_factory=_now_iso)

    def to_summary(self) -> str:
        """Format identity profile as readable text (for prompts/export)."""
        lines = []

        if self.persistent_concerns:
            top = ", ".join(tag for tag, _ in self.persistent_concerns[:5])
            lines.append(f"Persistent concerns: {top}")

        if self.core_beliefs:
            for content, conf in self.core_beliefs[:3]:
                lines.append(f"Core belief: {content} ({int(conf*100)}%)")

        if self.living_questions:
            for q in self.living_questions[:3]:
                lines.append(f"Living question: {q}")

        if self.lessons_accumulated > 0:
            lines.append(f"Accumulated {self.lessons_accumulated} lessons from experience")

        if self.growth_signal:
            lines.append(f"Growth: {self.growth_signal}")

        return "\n".join(lines) if lines else "Identity still forming."


@dataclass
class MemoryProfile:
    """Agent-specific memory characteristics.

    Different agents can have different 'minds' — different WM capacity,
    different encoding biases, different decay rates.
    """

    agent_id: str = "default"
    name: str = "Agent"

    # Cognitive parameters
    wm_nominal_capacity: int = 7
    """Nominal working memory capacity (soft gradient, not hard cap)."""

    encoding_bias: dict[str, float] = field(default_factory=dict)
    """Domains that get encoded deeper. e.g. {"technical": 0.1, "social": 0.05}"""

    retrieval_bias: dict[str, float] = field(default_factory=dict)
    """Domains retrieved more easily. e.g. {"python": 0.1}"""

    decay_rate_global: float = 1.0
    """Global decay rate multiplier. <1.0 = slower forgetting."""

    core_schemas: list[str] = field(default_factory=list)
    """Schema IDs this agent always loads."""

    emotional_dimensions: list[str] = field(default_factory=lambda: [
        "curiosity", "restlessness", "warmth",
        "clarity", "creative_flow", "isolation",
    ])

    def to_dict(self) -> dict:
        return {
            "agent_id": self.agent_id,
            "name": self.name,
            "wm_nominal_capacity": self.wm_nominal_capacity,
            "encoding_bias": self.encoding_bias,
            "retrieval_bias": self.retrieval_bias,
            "decay_rate_global": self.decay_rate_global,
            "core_schemas": self.core_schemas,
            "emotional_dimensions": self.emotional_dimensions,
        }

    @classmethod
    def from_dict(cls, d: dict) -> MemoryProfile:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


@dataclass
class AgentIdentity:
    """Portable agent identity. MLP-compatible.

    The kernel contains invariants that persist even if all other memory
    is reset — the agent's constitutional values, boundaries, and
    core preferences. Append-only: new invariants can be added but
    existing ones are never removed.
    """

    kernel_id: str = field(default_factory=lambda: f"kernel_{_gen_ulid()}")

    invariants: dict = field(default_factory=dict)
    """Values, boundaries, preferences. Protected, append-only.
    Example: {"values": ["honesty", "curiosity"], "boundaries": ["no deception"]}"""

    evolution_rules: dict = field(default_factory=dict)
    """Rules governing how identity can change.
    Example: {"epoch_transition": "requires_significant_event"}"""

    epoch_state: EpochState = field(default_factory=EpochState)
    """Current developmental phase."""

    epoch_history: list[EpochState] = field(default_factory=list)
    """Previous epochs (the geological layers of identity)."""

    memory_profile: MemoryProfile = field(default_factory=MemoryProfile)
    """Agent-specific cognitive parameters."""

    def transition_epoch(self, trigger: str) -> None:
        """Transition to a new developmental epoch.

        The current epoch is archived and a new one begins.
        """
        self.epoch_state.trigger_event = trigger
        self.epoch_history.append(self.epoch_state)

        self.epoch_state = EpochState(
            epoch_number=self.epoch_state.epoch_number + 1,
        )

    def to_dict(self) -> dict:
        return {
            "kernel_id": self.kernel_id,
            "invariants": json.dumps(self.invariants),
            "evolution_rules": json.dumps(self.evolution_rules),
            "epoch_state": json.dumps(self.epoch_state.to_dict()),
            "epoch_history": json.dumps(
                [e.to_dict() for e in self.epoch_history]
            ),
            "memory_profile": json.dumps(self.memory_profile.to_dict()),
        }

    @classmethod
    def from_dict(cls, d: dict) -> AgentIdentity:
        invariants = d.get("invariants", "{}")
        if isinstance(invariants, str):
            invariants = json.loads(invariants)

        evolution_rules = d.get("evolution_rules", "{}")
        if isinstance(evolution_rules, str):
            evolution_rules = json.loads(evolution_rules)

        epoch_state = d.get("epoch_state", "{}")
        if isinstance(epoch_state, str):
            epoch_state = json.loads(epoch_state)

        epoch_history = d.get("epoch_history", "[]")
        if isinstance(epoch_history, str):
            epoch_history = json.loads(epoch_history)

        profile = d.get("memory_profile", "{}")
        if isinstance(profile, str):
            profile = json.loads(profile)

        return cls(
            kernel_id=d.get("kernel_id", f"kernel_{_gen_ulid()}"),
            invariants=invariants,
            evolution_rules=evolution_rules,
            epoch_state=EpochState.from_dict(epoch_state),
            epoch_history=[EpochState.from_dict(e) for e in epoch_history],
            memory_profile=MemoryProfile.from_dict(profile),
        )
