"""Bootstrap a complete Mnemos agent stack.

Creates the workspace directory structure, initializes the Mnemos database,
copies and personalizes identity templates, and outputs instructions for
setting up OpenClaw crons.

Usage:
    python -m mnemos.setup.bootstrap --agent-name Nova --workspace ~/nova --user-name Riley

Or via the CLI:
    mnemos bootstrap --agent-name Nova --workspace ~/nova --user-name Riley
"""

from __future__ import annotations

import argparse
import shutil
import sys
from datetime import datetime
from datetime import timezone as _utc_tz
from pathlib import Path

# Template files and their destination paths relative to workspace
_TEMPLATE_MAP = {
    "SOUL.md": "SOUL.md",
    "IDENTITY.md": "IDENTITY.md",
    "MEMORY.md": "MEMORY.md",
    "AGENTS.md": "AGENTS.md",
    "HEARTBEAT.md": "HEARTBEAT.md",
    "active-context.md": "memory/active-context.md",
}

# Directories to create under the workspace
_WORKSPACE_DIRS = [
    "memory",
    "daily",
    "inner_life",
]

# .env template contents
_ENV_TEMPLATE = """\
# Mnemos Agent Configuration
# Generated by: mnemos bootstrap

# ── Agent Identity ──
MNEMOS_AGENT_ID={agent_id}
MNEMOS_AGENT_NAME={agent_name}

# ── Paths ──
MNEMOS_DB_PATH={db_path}
MNEMOS_WORKSPACE={workspace}
# MNEMOS_SHARED_DB=~/.mnemos/shared.db

# ── LLM Provider (pick one) ──
# MNEMOS_LLM_PROVIDER=openrouter
# OPENROUTER_API_KEY=your-key-here
# MNEMOS_MODEL=anthropic/claude-sonnet-4-5

# MNEMOS_LLM_PROVIDER=anthropic
# ANTHROPIC_API_KEY=your-key-here

# MNEMOS_LLM_PROVIDER=openai
# OPENAI_API_KEY=your-key-here

# ── Embedding Support (optional) ──
# GOOGLE_API_KEY=your-key-here

# ── Substrate Configuration ──
# MNEMOS_SUBSTRATE_DECAY_RATE=0.01
# MNEMOS_SUBSTRATE_BASE_TEMPERATURE=0.5
# MNEMOS_SUBSTRATE_MAX_ENGRAMS_PER_TICK=200
"""


def _find_templates_dir() -> Path:
    """Locate the templates directory.

    Checks in order:
    1. Adjacent to the mnemos package (repo root /templates/)
    2. Inside the package (mnemos/setup/templates/ — for installed packages)
    """
    # Repo layout: mnemos/ is a sibling of templates/
    repo_root = Path(__file__).resolve().parent.parent.parent
    templates = repo_root / "templates"
    if templates.is_dir():
        return templates

    # Fallback: bundled templates
    bundled = Path(__file__).resolve().parent / "templates"
    if bundled.is_dir():
        return bundled

    raise FileNotFoundError(
        "Cannot find templates directory. Expected at "
        f"{repo_root / 'templates'} or {bundled}"
    )


def _personalize(content: str, replacements: dict[str, str]) -> str:
    """Replace all {placeholders} in template content."""
    result = content
    for key, value in replacements.items():
        result = result.replace(f"{{{key}}}", value)
    return result


def bootstrap(
    agent_name: str,
    workspace: str,
    user_name: str = "User",
    db_path: str | None = None,
    agent_id: str | None = None,
    timezone: str = "America/New_York",
) -> dict:
    """Bootstrap a complete agent stack.

    Args:
        agent_name: Human-readable name for the agent.
        workspace: Path to the workspace directory.
        user_name: Name of the user who owns this agent.
        db_path: Path to the Mnemos database. Defaults to ~/.mnemos/{agent_id}.db
        agent_id: Machine-readable agent ID. Defaults to lowercase agent_name.
        timezone: Timezone for cron scheduling.

    Returns:
        Dict with paths created and status information.
    """
    workspace_path = Path(workspace).expanduser().resolve()
    agent_id = agent_id or agent_name.lower().replace(" ", "-")
    db_path = db_path or f"~/.mnemos/{agent_id}.db"
    now = datetime.now(tz=_utc_tz.utc).strftime("%Y-%m-%d")

    result = {
        "workspace": str(workspace_path),
        "agent_name": agent_name,
        "agent_id": agent_id,
        "db_path": db_path,
        "dirs_created": [],
        "files_created": [],
        "errors": [],
    }

    # ── Step 1: Create workspace directories ──
    for subdir in _WORKSPACE_DIRS:
        dir_path = workspace_path / subdir
        dir_path.mkdir(parents=True, exist_ok=True)
        result["dirs_created"].append(str(dir_path))

    # ── Step 2: Initialize Mnemos database ──
    try:
        from ..store.sqlite_store import EngramStore

        real_db_path = Path(db_path).expanduser()
        real_db_path.parent.mkdir(parents=True, exist_ok=True)
        store = EngramStore(str(real_db_path))
        store.close()
        result["db_initialized"] = True
    except Exception as e:
        result["db_initialized"] = False
        result["errors"].append(f"Database init failed: {e}")

    # ── Step 3: Copy and personalize templates ──
    replacements = {
        "agent_name": agent_name,
        "agent_id": agent_id,
        "user_name": user_name,
        "workspace": str(workspace_path),
        "db_path": db_path,
        "date": now,
        "timestamp": datetime.now(tz=_utc_tz.utc).isoformat(),
        "timezone": timezone,
        "model": "default",
        "one-line description of role": f"Primary agent for {user_name}",
    }

    try:
        templates_dir = _find_templates_dir()
    except FileNotFoundError as e:
        result["errors"].append(str(e))
        return result

    for template_name, dest_rel in _TEMPLATE_MAP.items():
        template_path = templates_dir / template_name
        dest_path = workspace_path / dest_rel

        if dest_path.exists():
            # Don't overwrite existing identity files
            result["files_created"].append(f"{dest_path} (skipped — already exists)")
            continue

        if not template_path.exists():
            result["errors"].append(f"Template not found: {template_path}")
            continue

        content = template_path.read_text()
        personalized = _personalize(content, replacements)

        dest_path.parent.mkdir(parents=True, exist_ok=True)
        dest_path.write_text(personalized)
        result["files_created"].append(str(dest_path))

    # ── Step 4: Create .env template ──
    env_path = workspace_path / ".env"
    if not env_path.exists():
        env_content = _ENV_TEMPLATE.format(
            agent_id=agent_id,
            agent_name=agent_name,
            db_path=db_path,
            workspace=str(workspace_path),
        )
        env_path.write_text(env_content)
        result["files_created"].append(str(env_path))
    else:
        result["files_created"].append(f"{env_path} (skipped — already exists)")

    # ── Step 5: Generate cron installation instructions ──
    result["cron_instructions"] = _generate_cron_instructions(
        agent_name=agent_name,
        agent_id=agent_id,
        workspace=str(workspace_path),
        timezone=timezone,
    )

    return result


def _generate_cron_instructions(
    agent_name: str,
    agent_id: str,
    workspace: str,
    timezone: str,
) -> str:
    """Generate human-readable instructions for setting up OpenClaw crons."""
    from .cron_installer import generate_install_commands

    commands = generate_install_commands(
        agent_name=agent_name,
        agent_id=agent_id,
        workspace=workspace,
        timezone=timezone,
    )
    return commands


def print_result(result: dict) -> None:
    """Print bootstrap results in a human-friendly format."""
    print(f"\n{'='*60}")
    print(f"  Mnemos Agent Stack — {result['agent_name']}")
    print(f"{'='*60}\n")

    print(f"  Agent ID:   {result['agent_id']}")
    print(f"  Workspace:  {result['workspace']}")
    print(f"  Database:   {result['db_path']}")
    print(f"  DB Ready:   {'yes' if result.get('db_initialized') else 'no'}")
    print()

    if result["dirs_created"]:
        print("  Directories:")
        for d in result["dirs_created"]:
            print(f"    + {d}")
        print()

    if result["files_created"]:
        print("  Files:")
        for f in result["files_created"]:
            print(f"    + {f}")
        print()

    if result["errors"]:
        print("  Errors:")
        for e in result["errors"]:
            print(f"    ! {e}")
        print()

    if result.get("cron_instructions"):
        print("  OpenClaw Cron Setup:")
        print("  " + "-" * 40)
        for line in result["cron_instructions"].strip().split("\n"):
            print(f"  {line}")
        print()

    print(f"{'='*60}")
    print("  Next steps:")
    print("  1. Edit .env with your API keys")
    print("  2. Review and customize SOUL.md and IDENTITY.md")
    print("  3. Install the OpenClaw crons (commands above)")
    print("  4. Run: mnemos stats --agent-id " + result["agent_id"])
    print(f"{'='*60}\n")


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for bootstrap."""
    parser = argparse.ArgumentParser(
        prog="mnemos-bootstrap",
        description="Bootstrap a complete Mnemos agent stack",
    )
    parser.add_argument(
        "--agent-name",
        required=True,
        help="Human-readable agent name (e.g., Nova)",
    )
    parser.add_argument(
        "--workspace",
        required=True,
        help="Path to the agent's workspace directory",
    )
    parser.add_argument(
        "--user-name",
        default="User",
        help="Name of the user (default: User)",
    )
    parser.add_argument(
        "--db-path",
        default=None,
        help="Path to Mnemos database (default: ~/.mnemos/{agent_id}.db)",
    )
    parser.add_argument(
        "--agent-id",
        default=None,
        help="Machine-readable agent ID (default: lowercase agent name)",
    )
    parser.add_argument(
        "--timezone",
        default="America/New_York",
        help="Timezone for cron scheduling (default: America/New_York)",
    )

    args = parser.parse_args(argv)

    result = bootstrap(
        agent_name=args.agent_name,
        workspace=args.workspace,
        user_name=args.user_name,
        db_path=args.db_path,
        agent_id=args.agent_id,
        timezone=args.timezone,
    )

    print_result(result)

    return 1 if result["errors"] else 0


if __name__ == "__main__":
    sys.exit(main())
